---
- hosts: pibox
  remote_user: pi
  become: true
  tasks:
    - include: deploy/packages.yml
    # - include: deploy/filesystem.yml basedir={{ basedir }}
    # - include: deploy/npm.yml basedir={{ basedir }}
    # - include: deploy/backup_mechaoperator.yml basedir={{ basedir }}
    # - include: deploy/mechaoperator.yml basedir={{ basedir }}
    # - include: deploy/helpers.yml basedir={{ basedir }}
